INSERT INTO dim_source (
    source_key,
    source_name,
    category,
    source_type,
    reliability_class,
    license,
    url,
    update_frequency,
    allowed_usage,
    notes
) VALUES
    (
        'wri_global_power_plant_database',
        'WRI Global Power Plant Database',
        'energy',
        'open',
        'P',
        'to_verify',
        'to_verify: https://datasets.wri.org/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify official dataset URL, license, update cadence, and continued maintenance before ingestion.'
    ),
    (
        'peeringdb',
        'PeeringDB',
        'internet_infrastructure',
        'community',
        'P',
        'to_verify',
        'to_verify: https://www.peeringdb.com/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify API terms, redistribution permissions, and attribution requirements before ingestion.'
    ),
    (
        'pch_ixp_directory',
        'Packet Clearing House IXP Directory',
        'internet_infrastructure',
        'open',
        'P',
        'to_verify',
        'to_verify: https://www.pch.net/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify directory URL, license, and permitted use before ingestion.'
    ),
    (
        'osm_openinframap',
        'OpenStreetMap / OpenInfraMap',
        'infrastructure_basemap',
        'community',
        'P',
        'to_verify',
        'to_verify: https://www.openstreetmap.org/ and https://openinframap.org/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify ODbL obligations, derived database treatment, and OpenInfraMap data access path before ingestion.'
    ),
    (
        'global_energy_monitor',
        'Global Energy Monitor',
        'energy',
        'open',
        'P',
        'to_verify',
        'to_verify: https://globalenergymonitor.org/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify tracker-specific licenses and download terms before ingestion.'
    ),
    (
        'usgs_mineral_commodity_summaries',
        'USGS Mineral Commodity Summaries',
        'primary_resources',
        'official',
        'P',
        'to_verify',
        'to_verify: https://www.usgs.gov/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify exact publication URL, public-domain status, and citation requirements before ingestion.'
    ),
    (
        'wri_aqueduct',
        'WRI Aqueduct',
        'water_risk',
        'open',
        'P',
        'to_verify',
        'to_verify: https://www.wri.org/aqueduct',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify download endpoints, license, and indicator definitions before ingestion.'
    ),
    (
        'hydrosheds',
        'HydroSHEDS',
        'water_risk',
        'open',
        'P',
        'to_verify',
        'to_verify: https://www.hydrosheds.org/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify HydroSHEDS version, license, and raster/vector distribution terms before ingestion.'
    ),
    (
        'world_bank_wgi',
        'World Bank Worldwide Governance Indicators',
        'geopolitical_risk',
        'official',
        'P',
        'to_verify',
        'to_verify: https://www.worldbank.org/',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify exact API or download source, license, and indicator methodology before ingestion.'
    ),
    (
        'cloud_provider_official_regions',
        'Cloud provider official region pages',
        'cloud_infrastructure',
        'official',
        'P',
        'to_verify',
        'to_verify: provider-specific official region pages',
        'to_verify',
        'metadata_registry_only_until_license_verified',
        'Initial placeholder. Verify provider-by-provider terms and whether locations are region-level, zone-level, or marketing-level disclosures.'
    )
ON CONFLICT (source_key) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    category = EXCLUDED.category,
    source_type = EXCLUDED.source_type,
    reliability_class = EXCLUDED.reliability_class,
    license = EXCLUDED.license,
    url = EXCLUDED.url,
    update_frequency = EXCLUDED.update_frequency,
    allowed_usage = EXCLUDED.allowed_usage,
    notes = EXCLUDED.notes;
